services:
  app:
    container_name: minibank
    image: example.com/minibank:latest
    environment:
      spring.profiles.active: "docker"
      DB_USERNAME: "hydra"
      DB_PASSWORD: "cerberus"
      DB_URL: "jdbc:postgresql://postgresql:5432/local"
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
  postgresql:
    container_name: postgresql
    image: postgres:alpine
    environment:
      POSTGRES_USER: hydra
      POSTGRES_PASSWORD: cerberus
      POSTGRES_DB: local
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: hydra@mail.com
      PGADMIN_DEFAULT_PASSWORD: cerberus
    ports:
      - "8888:80"